name: Laravel

on:
  workflow_dispatch:

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: install laravel provec
        run: composer create-project  laravel/laravel blog "10.*"
      - name: ls_blog
        run: |
          ls -la /etc/ssl/certs/ca-certificates.crt
          mv ./blog/*  ./
          mv ./blog/.editorconfig  ./.editorconfig
          mv ./blog/.env  ./.env
          mv ./blog/.env.example  ./.env.example
          mv ./blog/.gitattributes  ./.gitattributes
          mv ./blog/.gitignore  ./.gitignore
          echo "./blog/*" >> .gitignore
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: push
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@users.noreply.github.com
          echo "----------------------------------1----------------------------------------------"
          git status
          echo "----------------------------------add----------------------------------------------"
          git add ./
          echo "----------------------------------2----------------------------------------------"
          git status
          git restore --staged README.md
          git restore README.md
          git checkout -- README.md
          echo "----------------------------------3----------------------------------------------"
          git status
          git commit -m "init laravel 10.*"
          echo "----------------------------------log----------------------------------------------"
          git log
          echo "----------------------------------push----------------------------------------------"
          git push origin

